---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu"
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: install apache and tmux package
    tags: apache, tmux
    package:
      name: 
        - "{{ apache_pack }}"
        - "{{ tmux_pack }}"
      state: latest  
      update_cache: yes

  - name: copy index.html to default server page
    tags: apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/host1/index.html
      owner: root
      group: root
      mode: 0644  
