---

- hosts: all
  become: true
  tasks:

  - name: update cache, install apache and tmux package
    tags: webpack
    package:
      name: 
        - "{{ apache_pack }}"
        - "{{ tmux_pack }}"
      state: latest  
      update_cache: yes

  - name: copy index.html to default server page
    tags: apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/host1/index.html
      owner: root
      group: root
      mode: 0644
