---

- hosts: all
  become: true
  tasks:

  - name: update cache, install apache and tmux package
    tags: webpack
    package:
      name: 
        - "{{ apache_pack }}"
        - "{{ tmux_pack }}"
      state: latest  
      update_cache: yes
